services:
  metabase-edutech:
    image: metabase/metabase:latest
    container_name: metabase-edutech
    ports:
      - "3010:3000"
    volumes:
      - ./metabase-data:/metabase.db
    restart: unless-stopped
